# CLASE 07 Creación de Arrays
## Prof. Andrés Mena Abarca
### Estudiante:  Karla Salazar Chavarria

### Crear un array a partir de una lista

In [2]:
import numpy as np



### Crear un array de ceros de tamaño 5x5

In [3]:
#Código crear un array de ceros de tamaño 5x5

array_ceros = np.zeros((5,5))
print (array_ceros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Crear un array de unos de tamaño 3x3

In [6]:
#Código crear un array de unos de tamaño 3x3
array_unos = np.ones((2,3))
print(array_unos)

[[1. 1. 1.]
 [1. 1. 1.]]


### Crear un array con valores espaciados uniformemente de 0 a 9

In [10]:
#Código rear un array con valores espaciados uniformemente de 0 a 9
array_linear = np.linspace(0,9,10)
print(array_linear)
# se usa para poder graficar con datos agrupados, por ejemplo de 0 a 5 anios tanto %

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### #Crear un array con 6 valores espaciados linealmente entre 0 y 1


In [ ]:
#Código crear un array con 6 valores espaciados linealmente entre 0 y 1
array_reto = np.linspace(0,1,1000)
print(array_reto)
# ejemplo para coordenadas GPS

[0.         0.001001   0.002002   0.003003   0.004004   0.00500501
 0.00600601 0.00700701 0.00800801 0.00900901 0.01001001 0.01101101
 0.01201201 0.01301301 0.01401401 0.01501502 0.01601602 0.01701702
 0.01801802 0.01901902 0.02002002 0.02102102 0.02202202 0.02302302
 0.02402402 0.02502503 0.02602603 0.02702703 0.02802803 0.02902903
 0.03003003 0.03103103 0.03203203 0.03303303 0.03403403 0.03503504
 0.03603604 0.03703704 0.03803804 0.03903904 0.04004004 0.04104104
 0.04204204 0.04304304 0.04404404 0.04504505 0.04604605 0.04704705
 0.04804805 0.04904905 0.05005005 0.05105105 0.05205205 0.05305305
 0.05405405 0.05505506 0.05605606 0.05705706 0.05805806 0.05905906
 0.06006006 0.06106106 0.06206206 0.06306306 0.06406406 0.06506507
 0.06606607 0.06706707 0.06806807 0.06906907 0.07007007 0.07107107
 0.07207207 0.07307307 0.07407407 0.07507508 0.07607608 0.07707708
 0.07807808 0.07907908 0.08008008 0.08108108 0.08208208 0.08308308
 0.08408408 0.08508509 0.08608609 0.08708709 0.08808809 0.0890

# Operaciones Básicas

### Realizar una suma, resta, multiplicación y división entre dos arrays

In [12]:
array_salario = np.array([50,40,20])
array_propinas = np.array([6,4,9])

#Código realizar una suma, resta, multiplicación y división entre dos arrays

# Salida
'''
print("La suma es: ",suma)
print("La resta es: ",resta)
print("La multiplicacion es: ",multiplicacion)
print("La division es: ",division)
'''

suma = array_salario + array_propinas
print("La suma es: ",suma)

resta = array_salario - array_propinas
print("La resta es: ",resta)

multiplicacion = array_salario * array_propinas
print("La multiplicacion es: ",multiplicacion)

division = array_salario / array_propinas
print("La division es: ",division)


La suma es:  [56 44 29]
La resta es:  [44 36 11]
La multiplicacion es:  [300 160 180]
La division es:  [ 8.33333333 10.          2.22222222]


In [ ]:
#Calcular el producto punto de dos arrays


In [ ]:
#Transponer un array


# Operaciones Estadísticas

In [ ]:
#Calcular la media, suma, valor mínimo y valor máximo de un array


# Crear un array NumPy
array_numeros = np.array([5, 2, 4, 1, 3])

# Calcular la media
media = np.mean(array_numeros)
print(f'La media aritmética es: {media}')


# Calcular la suma
suma = np.sum(array_numeros)
print(f'La suma de la colección de datos es: {suma}')

# Calcular el valor mínimo
minimo = np.min(array_numeros)
print(f'La valor minimo de la coleccion es: {minimo}')

# Calcular el valor máximo
maximo = np.max(array_numeros)
print(f'La valor maximo de la coleccion es: {maximo}')


'''
# Mostrar los resultados
print("La media es:", media)
print("La suma es:", suma)
print("El valor mínimo es:", valor_minimo)
print("El valor máximo es:", valor_maximo)
'''


La media aritmética es: 3.0
La suma de la colección de datos es: 15
La valor minimo de la coleccion es: 1
La valor maximo de la coleccion es: 5


'\n# Mostrar los resultados\nprint("La media es:", media)\nprint("La suma es:", suma)\nprint("El valor mínimo es:", valor_minimo)\nprint("El valor máximo es:", valor_maximo)\n'

In [20]:
#Cambiar la forma de un array "reshape"


# Crear un array original
array_original = np.array([1, 2, 3, 4, 5, 6])

# Nueva forma deseada (2 filas y 3 columnas)
array_nuevo = array_original.reshape(2,3)
print(f'El valor es: {array_nuevo}')

'''
# Imprimir el array original y el reshapeado
print("Array original:", array_original)
print("Array reshapeado:", array_reshapeado)
'''

El valor es: [[1 2 3]
 [4 5 6]]


'\n# Imprimir el array original y el reshapeado\nprint("Array original:", array_original)\nprint("Array reshapeado:", array_reshapeado)\n'

# Álgebra Lineal

### Calcular el determinante de una matriz 2x2

In [ ]:
nuevo_array = np.array([[1,2],[2,5]])

#Código para calcular el determinante de una matriz 2x2

#print(determinante)





### Calcular la matriz inversa de una matriz 3x3

In [ ]:
# Definir la matriz 3x3


# Calcular la matriz inversa


# Imprimir la matriz inversa



### Calcular los valores propios y vectores propios de una matriz 4x4

In [ ]:

# Definir la matriz 4x4
matriz_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Calcular valores propios y vectores propios


# Separar valores propios y vectores propios
 # Parte real de los valores propios complejos
  # Parte real de los vectores propios complejos

# Imprimir resultados
'''
print("Valores propios:", autovalores)
print("Vectores propios:")
for i in range(len(autovectores)):
    print(f"Vector propio {i+1}:", autovectores[i])
'''

# Funciones Universales

In [ ]:
# Crear un array con ángulos
array_angulos = np.array([0, np.pi/2, np.pi])

# Calcular el seno de los ángulos


# Calcular el coseno de los ángulos


# Calcular la exponencial de los ángulos


# Calcular el logaritmo natural de los ángulos




In [ ]:
#Realizar indexación y slicing en un array 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


# Obtener la primera fila del array


# Obtener la última columna del array
  # [3, 6, 9]

# Obtener una submatriz que contiene la segunda fila y las dos primeras columnas
  # [4, 5]

# Imprimir los subconjuntos de datos extraídos


# Generación de Números Aleatorios

In [ ]:
#Generar un array de 10 números enteros aleatorios entre 1 y 100


In [ ]:
#Generar una matriz 2x3 con números aleatorios uniformemente distribuidos entre 0 y 1


In [ ]:
#Generar un array de 5 números aleatorios con distribución normal (media 0, desviación estándar 1)



# EJERCICIOS REALES O PRACTICOS
# Preferencias de los consumidores

In [22]:
# Preferencias peliculas Mariana [accion, comedia, drama]

mariana = np.array([7,9,2])

avatar = np.array([10,1,5]) # mas accion y menos comedia

brave_heart = np.array([8, 1, 7]) # mas accion y menos comedia


# Calcular la similitud de cada pelicula con los gustos de Mariana
similitud_p1 = np.dot(mariana,avatar)
similitud_p2 = np.dot(mariana,brave_heart)

print(f'La similitud con respecto a la pelicula avatar es: {similitud_p1}')

print(f'La similitud con respecto a la pelicula brave es: {similitud_p2}')

if similitud_p1 > similitud_p2:
    print('Le recomendamos Avatar')
else:
    print('Le recomendamos Brave')




La similitud con respecto a la pelicula avatar es: 89
La similitud con respecto a la pelicula brave es: 79
Le recomendamos Avatar


# Caso estudio relación

In [23]:
import numpy as np
#Datos Tipo Cambio Dolar Ultimos 10 meses | IPC , metrica mesual


tipo_cambio = np.array([506.96,505.00,504.27,505.52,506.23,506.23,506.23,506.58,506.87,507.25])
ipc = np.array([109.46,109.55,109.71,109.57,109.70,109.33,108.85, 109.36,110.39,110.79])


#Calcular coeficiente de correlación
correlacion =  np.corrcoef(tipo_cambio,ipc)[0,1]


print(f'Coeficiente de correlación: {correlacion:.2f}')

Coeficiente de correlación: 0.32


# Caso #3 Estudio de Horas vrs Notas

In [24]:
#Datos: Horas de estudio y Notas Obtenidas


horas_estudio = np.array([1,2,3,4,5,6,7,8,9,10]) # Horas de estudio
notas = np.array([50,55,60,63,67,72,75,78,81,85]) # Notas Obtenida


#Cálculo crecimiento del promedio del puntuje por hora de estudio
diferencias_notas = np.diff(notas)# Difrencias entre notas consecutivas
incremento_notas = np.average(diferencias_notas)


#Estimación del puntaje si estudio 12 horas
proyeccion_estudio= 12
nota_estimada = (proyeccion_estudio - max(horas_estudio)) * incremento_notas + max(notas)



print(f"El incremento del promedio por cada hora de estudio {incremento_notas:.2f}")
print(nota_estimada)

El incremento del promedio por cada hora de estudio 3.89
92.77777777777777
